/**
 * Selection logic for the done janitor's idle-workspace sweep: which workspace records are idle
 * enough to archive, which rule made them so, and whether a Paseo-owned worktree's work is backed
 * up well enough for its directory to go. Pure — no I/O, no clock reads; AgentDoneJanitor reads
 * the facts and passes `nowMs` in. See docs/done-janitor.md, "Idle workspaces".
 *
 * Every doubt keeps the workspace: a pin, an agent at work, an unreadable timestamp, no activity
 * signal at all, a backup that does not cover every file.
 */

import type { WorktreeSnapshotResult } from "../remediation/contract.js";
import type { DoneJanitorProject, DoneJanitorWorkspace } from "../agent-done-janitor.js";
import {
  DONE_JANITOR_KEEP_LABEL,
  formatDuration,
  listDescendants,
  type DoneJanitorAgentView,
} from "./done-janitor-detector.js";

const HOUR_MS = 60 * 60_000;

/** The label the remediation ladder puts on every agent it starts (remediation/ladder.ts). */
export const REMEDIATION_LABEL = "paseo.remediation";

/**
 * How long a self-heal fixer must have been quiet before its workspace goes. The ladder polls its
 * agents every minute and reads the report from the finished agent; archiving first would read to
 * it as "archived before it reported" and send a person a false failure.
 */
export const FIXER_SETTLE_MS = 10 * 60_000;

/**
 * Directories whose ignored contents are regenerated by a build or an install. Anything else
 * ignored — `.env`, local settings, notes — may exist nowhere else.
 */
const BUILD_OUTPUT_DIRS: ReadonlySet<string> = new Set([
  "node_modules",
  "dist",
  "build",
  "target",
  "out-tsc",
  ".gradle",
  ".cxx",
  ".kotlin",
  "DerivedData",
  "Pods",
  ".expo",
  ".next",
  ".nuxt",
  ".svelte-kit",
  ".turbo",
  ".parcel-cache",
  ".cache",
  "coverage",
  "__pycache__",
  ".pytest_cache",
  ".mypy_cache",
  ".ruff_cache",
  ".venv",
  "venv",
  ".dart_tool",
  ".godot",
]);
const BUILD_OUTPUT_FILES: ReadonlySet<string> = new Set([".DS_Store"]);
const BUILD_OUTPUT_EXTENSIONS = [".pyc", ".pyo"] as const;

/** `agents.doneJanitor.workspaceSweep`. Every key is optional; the resolver owns the defaults. */
export interface DoneJanitorWorkspaceSweepConfig {
  enabled?: boolean;
  dryRun?: boolean;
  idleHours?: number;
  emptyIdleHours?: number;
  maxArchivesPerSweep?: number;
  projectGraceHours?: number;
  maxProjectRemovalsPerSweep?: number;
}

export interface ResolvedWorkspaceSweepConfig {
  enabled: boolean;
  /** The janitor's own `dryRun` makes the sweep dry too. */
  dryRun: boolean;
  /** Anything with agents, or in a git checkout. */
  idleMs: number;
  /** No unarchived agent and no git checkout: nothing in it to lose. */
  emptyIdleMs: number;
  maxArchivesPerSweep: number;
  /** How long a project stays after its last active workspace goes. */
  projectGraceMs: number;
  maxProjectRemovalsPerSweep: number;
}

export function resolveWorkspaceSweepConfig(janitor: {
  dryRun?: boolean;
  workspaceSweep?: DoneJanitorWorkspaceSweepConfig;
}): ResolvedWorkspaceSweepConfig {
  const sweep = janitor.workspaceSweep;
  return {
    enabled: sweep?.enabled ?? true,
    dryRun: (janitor.dryRun ?? false) || (sweep?.dryRun ?? false),
    idleMs: (sweep?.idleHours ?? 72) * HOUR_MS,
    emptyIdleMs: (sweep?.emptyIdleHours ?? 24) * HOUR_MS,
    maxArchivesPerSweep: sweep?.maxArchivesPerSweep ?? 10,
    projectGraceMs: (sweep?.projectGraceHours ?? 24) * HOUR_MS,
    maxProjectRemovalsPerSweep: sweep?.maxProjectRemovalsPerSweep ?? 10,
  };
}

/** Activity read from the workspace's directory. The git index is never one of them. */
export interface WorkspaceActivitySignals {
  /** HEAD's committer time; null when the directory is not in a git checkout. */
  headCommitMs: number | null;
  /** The directory's own mtime; null when it does not exist. */
  directoryMtimeMs: number | null;
}

export interface WorkspaceSweepFacts {
  workspace: DoneJanitorWorkspace;
  /** Every agent whose workspace this is, archived or not. */
  agents: readonly DoneJanitorAgentView[];
  /** Every agent the daemon knows, for the subagents of the ones in this workspace. */
  views: readonly DoneJanitorAgentView[];
  terminalCount: number;
  runningScriptCount: number;
  /** Null until read: the sweep reads the directory only for a workspace the rest cannot decide. */
  signals: WorkspaceActivitySignals | null;
}

export type WorkspaceSweepRule = "fixer" | "idle" | "empty";

export type WorkspaceSweepVerdict =
  | { kind: "active"; reason: string }
  | { kind: "needs-signals" }
  | { kind: "idle"; rule: WorkspaceSweepRule; idleForMs: number; reason: string };

/**
 * Whether a workspace record is idle enough to archive, and by which rule:
 * - `fixer`: every agent it ever held was started by the remediation ladder and none is at work.
 *   It goes once they settle, whatever its directory does: a fixer's directory is the home
 *   directory, whose mtime moves all day.
 * - `idle`: it has an unarchived agent or is a git checkout, and nothing moved for `idleMs`.
 * - `empty`: neither, and nothing moved for `emptyIdleMs`.
 */
export function classifyWorkspace(
  facts: WorkspaceSweepFacts,
  config: Pick<ResolvedWorkspaceSweepConfig, "idleMs" | "emptyIdleMs">,
  nowMs: number,
): WorkspaceSweepVerdict {
  const busy = workspaceBusyReason(facts);
  if (busy) return { kind: "active", reason: busy };

  const unarchived = facts.agents.filter((agent) => !agent.archived);
  const unreadable = unarchived.find((agent) => agent.lastActivityAtMs === null);
  if (unreadable) {
    return {
      kind: "active",
      reason: `agent ${unreadable.id} has no readable last-activity time`,
    };
  }
  if (isFixerWorkspace(facts.agents)) return classifyFixer(facts.agents, unarchived, nowMs);

  const recordActivity = [
    parseStamp(facts.workspace.createdAt),
    parseStamp(facts.workspace.updatedAt),
    ...unarchived.map((agent) => agent.lastActivityAtMs),
  ];
  const { signals } = facts;
  if (signals === null) {
    // The directory can only make the workspace newer. Read it only when the record alone does
    // not already keep the workspace under the shorter of the two thresholds.
    const newest = newestOf(recordActivity);
    const threshold = unarchived.length > 0 ? config.idleMs : config.emptyIdleMs;
    if (newest !== null && nowMs - newest < threshold) {
      return { kind: "active", reason: describeRecent(nowMs - newest, threshold) };
    }
    return { kind: "needs-signals" };
  }

  const newest = newestOf([...recordActivity, signals.headCommitMs, signals.directoryMtimeMs]);
  if (newest === null) return { kind: "active", reason: "it has no usable activity signal" };
  const gitCheckout = facts.workspace.kind !== "directory" || signals.headCommitMs !== null;
  const rule: WorkspaceSweepRule = unarchived.length > 0 || gitCheckout ? "idle" : "empty";
  const threshold = rule === "idle" ? config.idleMs : config.emptyIdleMs;
  const idleForMs = nowMs - newest;
  if (idleForMs < threshold) {
    return { kind: "active", reason: describeRecent(idleForMs, threshold) };
  }
  const reason =
    rule === "idle"
      ? `idle for ${formatDuration(idleForMs)}`
      : `no agents and no git checkout, idle for ${formatDuration(idleForMs)}`;
  return { kind: "idle", rule, idleForMs, reason };
}

function classifyFixer(
  agents: readonly DoneJanitorAgentView[],
  unarchived: readonly DoneJanitorAgentView[],
  nowMs: number,
): WorkspaceSweepVerdict {
  const newestUnarchived = newestOf(unarchived.map((agent) => agent.lastActivityAtMs));
  if (newestUnarchived !== null && nowMs - newestUnarchived < FIXER_SETTLE_MS) {
    return {
      kind: "active",
      reason: `its self-heal fixer stopped ${formatDuration(nowMs - newestUnarchived)} ago; it settles for ${formatDuration(FIXER_SETTLE_MS)} so the ladder reads its report first`,
    };
  }
  const newest = newestOf(agents.map((agent) => agent.lastActivityAtMs));
  return {
    kind: "idle",
    rule: "fixer",
    idleForMs: newest === null ? 0 : Math.max(0, nowMs - newest),
    reason: "a self-heal fixer's workspace, and every fixer in it is finished",
  };
}

/** Every agent it ever held was started by the remediation ladder. */
function isFixerWorkspace(agents: readonly DoneJanitorAgentView[]): boolean {
  return (
    agents.length > 0 &&
    agents.every((agent) => Object.prototype.hasOwnProperty.call(agent.labels, REMEDIATION_LABEL))
  );
}

/**
 * What keeps the workspace whatever its age: a pin, an agent at work or about to be woken, an
 * orchestrator whose fleet is still loaded, a terminal, a script. Null when nothing does.
 */
export function workspaceBusyReason(
  facts: Pick<
    WorkspaceSweepFacts,
    "workspace" | "agents" | "views" | "terminalCount" | "runningScriptCount"
  >,
): string | null {
  if (facts.workspace.pinnedAt) return "it is pinned";
  const unarchived = facts.agents.filter((agent) => !agent.archived);
  for (const agent of unarchived) {
    if (Object.prototype.hasOwnProperty.call(agent.labels, DONE_JANITOR_KEEP_LABEL)) {
      return `agent ${agent.id} is pinned with ${DONE_JANITOR_KEEP_LABEL}`;
    }
    const working = agentWorkingReason(agent);
    if (working) return `agent ${agent.id} ${working}`;
    if (agent.hasSchedule) return `agent ${agent.id} has a schedule or heartbeat that will wake it`;
  }
  for (const agent of unarchived) {
    // Archiving the workspace archives the leader, and its subagents with it or out from under it.
    const live = listDescendants(agent.id, facts.views).find(
      (descendant) => descendant.live || agentWorkingReason(descendant) !== null,
    );
    if (live) return `agent ${agent.id} leads subagent ${live.id}, which is live`;
  }
  if (facts.terminalCount > 0) return `it has ${facts.terminalCount} open terminal(s)`;
  if (facts.runningScriptCount > 0) {
    return `it has ${facts.runningScriptCount} running script(s)`;
  }
  return null;
}

function agentWorkingReason(agent: DoneJanitorAgentView): string | null {
  if (agent.lifecycle === "running" || agent.lifecycle === "initializing") {
    return `is ${agent.lifecycle}`;
  }
  if (agent.busy) return "has a turn in flight";
  if (agent.pendingPermissionCount > 0) return "is waiting on a permission";
  if (agent.runningProviderSubagentCount > 0) {
    return `has ${agent.runningProviderSubagentCount} provider subagent(s) still running`;
  }
  if (agent.interruptedMidTurn) return "was cut off mid-turn by a daemon stop";
  return null;
}

/**
 * Whether archiving the workspace deletes its directory. Archive-by-scope deletes a worktree it
 * decides is Paseo-owned: by the record's flag, or, for an older record without it, by the path
 * lying under the Paseo worktrees root (workspace-archive-service.ts). Every other workspace
 * keeps its directory; only the record is archived.
 */
export function archiveDeletesDirectory(input: {
  workspace: Pick<DoneJanitorWorkspace, "kind" | "isPaseoOwnedWorktree">;
  pathInsidePaseoWorktrees: boolean;
}): boolean {
  // The flag first, whatever the kind: archive-by-scope reads it before the kind.
  if (input.workspace.isPaseoOwnedWorktree) return true;
  return input.workspace.kind === "worktree" && input.pathInsidePaseoWorktrees;
}

/** What a worktree holds that a snapshot cannot: see `describeUncoveredWork`. */
export interface SnapshotGaps {
  /** `git ls-files --others --ignored --exclude-standard --directory` entries. */
  ignored: readonly string[];
  /** Untracked directories that are git repositories of their own, as `dir/`. */
  nestedRepositories: readonly string[];
}

/**
 * Why a snapshot does not back up everything a dirty or unpushed worktree holds; null when it
 * does. The snapshot (worktree-snapshot.ts) covers HEAD, tracked changes and untracked files up
 * to its size cap. It never covers ignored files, so any ignored file outside build output is
 * work that would be lost with the directory, and it stores an untracked nested repository as a
 * pointer to a commit, not its files.
 */
export function describeUncoveredWork(input: {
  /** Null in a dry run, which takes no snapshot: only the gaps are judged. */
  snapshot: WorktreeSnapshotResult | null;
  /** Null when git could not list them. */
  gaps: SnapshotGaps | null;
}): string | null {
  const { snapshot } = input;
  if (snapshot?.kind === "failed") {
    return `its work is at risk and could not be snapshotted: ${snapshot.error}`;
  }
  if (snapshot?.kind === "snapshotted" && snapshot.skippedFiles.length > 0) {
    return `${snapshot.skippedFiles.length} untracked file(s) too large for the snapshot (${listSome(snapshot.skippedFiles)})`;
  }
  if (input.gaps === null) return "its untracked and ignored files could not be listed";
  const { nestedRepositories } = input.gaps;
  if (nestedRepositories.length > 0) {
    return `${nestedRepositories.length} untracked nested repositor(ies) a snapshot holds only as a pointer (${listSome(nestedRepositories)})`;
  }
  const uncovered = input.gaps.ignored.filter((entry) => !isBuildOutputPath(entry));
  if (uncovered.length > 0) {
    return `${uncovered.length} ignored file(s) outside build output that no snapshot covers (${listSome(uncovered)})`;
  }
  return null;
}

/** Whether an ignored path is regenerated by a build or an install. Directories end with `/`. */
export function isBuildOutputPath(entry: string): boolean {
  const isDirectory = entry.endsWith("/");
  const segments = entry.split("/").filter(Boolean);
  const name = segments[segments.length - 1] ?? "";
  const directories = isDirectory ? segments : segments.slice(0, -1);
  if (directories.some((segment) => BUILD_OUTPUT_DIRS.has(segment))) return true;
  if (isDirectory) return false;
  return (
    BUILD_OUTPUT_FILES.has(name) ||
    BUILD_OUTPUT_EXTENSIONS.some((extension) => name.endsWith(extension))
  );
}

export type IdleProjectVerdict =
  | { kind: "keep"; reason: string }
  | { kind: "remove"; quietForMs: number; reason: string };

/**
 * Whether a project is sidebar clutter: not archived, not remote, no active workspace, and quiet
 * for `projectGraceMs` since the newest of its own timestamps and every one of its workspaces'.
 * An archived workspace's `archivedAt` is when it went, so the grace runs from the last one gone.
 * Removal is record-only and re-adding the project undoes it; its root is never looked at.
 */
export function idleProjectVerdict(
  project: DoneJanitorProject,
  workspaces: readonly DoneJanitorWorkspace[],
  config: Pick<ResolvedWorkspaceSweepConfig, "projectGraceMs">,
  nowMs: number,
): IdleProjectVerdict {
  if (project.archivedAt) return { kind: "keep", reason: "it is archived" };
  if (project.projectKey?.startsWith("remote:") || project.projectId.startsWith("remote:")) {
    return { kind: "keep", reason: "it is a remote project" };
  }
  const own = workspaces.filter((workspace) => workspace.projectId === project.projectId);
  if (own.some((workspace) => !workspace.archivedAt)) {
    return { kind: "keep", reason: "it has an active workspace" };
  }
  const newest = newestOf([
    parseStamp(project.createdAt),
    parseStamp(project.updatedAt),
    ...own.flatMap((workspace) => [
      parseStamp(workspace.createdAt),
      parseStamp(workspace.updatedAt),
      parseStamp(workspace.archivedAt),
    ]),
  ]);
  if (newest === null) return { kind: "keep", reason: "it has no usable activity signal" };
  const quietForMs = nowMs - newest;
  if (quietForMs < config.projectGraceMs) {
    return {
      kind: "keep",
      reason: `its last workspace went ${formatDuration(quietForMs)} ago; removed after ${formatDuration(config.projectGraceMs)}`,
    };
  }
  return {
    kind: "remove",
    quietForMs,
    reason: `it has had no active workspace for ${formatDuration(quietForMs)}`,
  };
}

function listSome(items: readonly string[]): string {
  const shown = items.slice(0, 3).join(", ");
  return items.length > 3 ? `${shown}, …` : shown;
}

function describeRecent(idleForMs: number, thresholdMs: number): string {
  return `active ${formatDuration(idleForMs)} ago; idle after ${formatDuration(thresholdMs)}`;
}

/** Absent is no signal. Present but unparseable reads as just now, which only ever delays. */
function parseStamp(value: string | null | undefined): number | null {
  if (!value) return null;
  const parsed = Date.parse(value);
  return Number.isFinite(parsed) ? parsed : Number.POSITIVE_INFINITY;
}

function newestOf(values: readonly (number | null)[]): number | null {
  const present = values.filter((value): value is number => value !== null);
  return present.length > 0 ? Math.max(...present) : null;
}
